// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTn7t9hQYCVWe7Mzd0umnU3mWhFkF3cA',
    appId: '1:220406370173:web:43de7dd5e9a357ecfc4614',
    messagingSenderId: '220406370173',
    projectId: 'notesapp-e939d',
    authDomain: 'notesapp-e939d.firebaseapp.com',
    storageBucket: 'notesapp-e939d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLv3rvtUH4hjKBpIyeFEKLjf91igd2C98',
    appId: '1:220406370173:android:30ab7887d54e6dcdfc4614',
    messagingSenderId: '220406370173',
    projectId: 'notesapp-e939d',
    storageBucket: 'notesapp-e939d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEekz4gWGEBQh_jRSrirr8r3E8WETHBkc',
    appId: '1:220406370173:ios:7562ab9955db37a8fc4614',
    messagingSenderId: '220406370173',
    projectId: 'notesapp-e939d',
    storageBucket: 'notesapp-e939d.appspot.com',
    iosClientId: '220406370173-318e0726tljlpilik55434t3tu86s6bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEekz4gWGEBQh_jRSrirr8r3E8WETHBkc',
    appId: '1:220406370173:ios:910cfb4a7fcf275dfc4614',
    messagingSenderId: '220406370173',
    projectId: 'notesapp-e939d',
    storageBucket: 'notesapp-e939d.appspot.com',
    iosClientId: '220406370173-5g1307omfalhjroj247bc3ri5e9vlbk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
